version: '2'

services:

##### TIER 1 #####
  nginx:
    image: nginx:1.10
    container_name: ech-web-nginx
    volumes:
      - ./data/log:/data/log
      - ./data/conf:/data/conf
      - ./data/conf/nginx/conf.d:/etc/nginx/conf.d
    command:
      - nginx
      - -g daemon off;
      - -c
      - /data/conf/nginx/nginx.conf
    volumes_from:
      - fpm:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - fpm

##### TIER 2 #####
  fpm:
    image: iwfwebsolutions/energie-ch-web:develop-latest
    container_name: ech-web-fpm
    volumes:
      - ./data/enech-web/cache:/app/app/cache
      - ./data/enech-web/data:/app/data
      - ./data/enech-web/logs:/app/app/logs
      - ./data/enech-web/sessions:/app/app/var/sessions
      - ./data/enech-web/web/media:/app/web/media
      - ./data:/data
      # Customize here
      - ./data/runtime/opcache.php:/app/web/opcache.php:ro
      #- ../../web:/app/web
    #command: php-fpm
    environment:
      - RUNTIME_ENVIRONMENT=local # dev is default
    links:
      - database

##### TIER 3 #####
  database:
    image: mysql:5.6
    container_name: ech-web-db
    ports:
      - "3306:3306" # expose for direct access locally
    volumes:
      - ./data/enech-web/mysql:/var/lib/mysql
      #- ./energiechapp/app/Resources/data/init_db.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: JKhgv%a.!hatzo-1l%
      MYSQL_DATABASE: EnergieCHweb_DB
      MYSQL_USER: uEnergieCHweb
      MYSQL_PASSWORD: HJougzdsf8GzEWc
